- type: web
    name: insta-chatapp-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'chidosky')"
      python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p $PORT instachat_backend.asgi:application